use_frameworks!

platform :ios, '8.0'

target 'NETURLSchemeHandler_Example' do
  pod 'NETURLSchemeHandler', :path => '../'

  target 'NETURLSchemeHandler_Tests' do
    inherit! :search_paths

    
  end
end
